### ISSUE TITLE
Not Clear How Bookings are Confirmed/Acknowledged from the Docs

### ISSUE THREAD

**Issue by umran** [MyAllocator/build2us-apidocs#1]
I am currently developing an OTA integration with the Build2Us API and I am confused as to how to keep track of a booking's status. That is, I am not sure how MyAllocator will acknowledge the confirmation status of a booking or cancellation after the OTA requests a booking or cancellation.

In the docs, there is a section called _NotifyBooking_ and if I understand it correctly, the OTA is supposed to send a request to MyAllocator with the property id and booking id whenever a booking is made or cancelled. MyAllocator then makes a GetBookingId request to the OTA, which responds with a booking object containing the booking information. And according to the docs, MyAllocator would then "Apply Booking to Inventory / Notify Property". It is not clear to me how the OTA receives a confirmation of the booking once the inventory is updated.

If you could please clarify this for me I would really appreciate it. Thanks!

**Comment by JacSoyYo** [comment]
Hi,

MyAllocator will call _GetBookingList_ (not _GetBookingId_ as documentation states) after receiving the _NotifyBooking_ request and booking can be considered delivered with that. MyAllocator will retry if something goes wrong. There is no confirmation to the OTA when the inventory is updated.

**Comment by umran** [comment]
Hi, thanks for clarifying that. 

The section of the documentation page I was referring to is [this](https://myallocator.github.io/build2us-apidocs/index.html#api-Getting_Started-Step_4__NotifyBooking), where it states that _GetBookingId_ is called, so I am confused.

How would the OTA know if the booking was not successful, for example due to overbooking? Is there any endpoint that can be used to check the status of bookings?

Thanks.

**Comment by JacSoyYo** [comment]
Most OTAs use their availability and don't check before creating bookings so MyAllocator accepts all bookings from OTA (even if OTA inventory is incorrect and there is no availability). Overbookings are notified and dealt with manually.

**Comment by JacSoyYo** [comment]
We accept all bookings, even in case of overbooking, and if this happens is dealt with manually.

**Comment by umran** [comment]
Thanks Jacobo. Does MyAllocator manually call up the OTA if that happens or is it the Hotel's responsibility?

**Comment by JacSoyYo** [comment]
There is no rule. If property contacts MyAllocator support they will handle it if possible.
